#!/bin/sh

CONTROLLER_PASSWORD_FILE="${MYSQL_CONTROLLER_PASSWORD_FILE:-/run/secrets/controller_password}"
CONTROLLER_USER="${MYSQL_CONTROLLER_USER:-platform_controller}"

if [ ! -r "$CONTROLLER_PASSWORD_FILE" ]; then
  echo "Missing MySQL controller password file" >&2
  return 1 2>/dev/null || exit 1
fi

CONTROLLER_PASSWORD="$(cat "$CONTROLLER_PASSWORD_FILE")"
if [ -z "$CONTROLLER_PASSWORD" ]; then
  echo "MySQL controller password is empty" >&2
  return 1 2>/dev/null || exit 1
fi

case "$CONTROLLER_USER" in
  *[!a-zA-Z0-9_]*|'')
    echo "Invalid MySQL controller username" >&2
    return 1 2>/dev/null || exit 1
    ;;
esac

sql_escape() {
  printf '%s' "$1" | sed "s/'/''/g"
}

CTRL_ESCAPED="$(sql_escape "$CONTROLLER_PASSWORD")"
ROOT_PASSWORD="${MYSQL_ROOT_PASSWORD:-$(cat "${MYSQL_ROOT_PASSWORD_FILE:-/run/secrets/root_password}")}" 

MYSQL_PWD="$ROOT_PASSWORD" mysql --protocol=socket -uroot <<SQL
CREATE USER IF NOT EXISTS '${CONTROLLER_USER}'@'172.%' IDENTIFIED BY '${CTRL_ESCAPED}' REQUIRE SSL;
CREATE USER IF NOT EXISTS '${CONTROLLER_USER}'@'10.%' IDENTIFIED BY '${CTRL_ESCAPED}' REQUIRE SSL;
CREATE USER IF NOT EXISTS '${CONTROLLER_USER}'@'192.168.%' IDENTIFIED BY '${CTRL_ESCAPED}' REQUIRE SSL;
ALTER USER '${CONTROLLER_USER}'@'172.%' IDENTIFIED BY '${CTRL_ESCAPED}' REQUIRE SSL;
ALTER USER '${CONTROLLER_USER}'@'10.%' IDENTIFIED BY '${CTRL_ESCAPED}' REQUIRE SSL;
ALTER USER '${CONTROLLER_USER}'@'192.168.%' IDENTIFIED BY '${CTRL_ESCAPED}' REQUIRE SSL;

REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${CONTROLLER_USER}'@'172.%';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${CONTROLLER_USER}'@'10.%';
REVOKE ALL PRIVILEGES, GRANT OPTION FROM '${CONTROLLER_USER}'@'192.168.%';

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER,
      SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE,
      CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER,
      EVENT, TRIGGER
ON *.* TO '${CONTROLLER_USER}'@'172.%' WITH GRANT OPTION;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER,
      SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE,
      CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER,
      EVENT, TRIGGER
ON *.* TO '${CONTROLLER_USER}'@'10.%' WITH GRANT OPTION;

GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER,
      SHOW DATABASES, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE,
      CREATE VIEW, SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER,
      EVENT, TRIGGER
ON *.* TO '${CONTROLLER_USER}'@'192.168.%' WITH GRANT OPTION;

DROP USER IF EXISTS '${CONTROLLER_USER}'@'%';
FLUSH PRIVILEGES;
SQL

unset ROOT_PASSWORD CONTROLLER_PASSWORD CTRL_ESCAPED

echo "MySQL controller account is restricted to private RFC1918 networks"
