storage:
  dbPath: /data/db
  wiredTiger:
    engineConfig:
      cacheSizeGB: 1

net:
  port: 27017
  bindIpAll: true

processManagement:
  timeZoneInfo: /usr/share/zoneinfo

setParameter:
  diagnosticDataCollectionEnabled: false
