storage:
  dbPath: /data/db
  wiredTiger:
    engineConfig:
      cacheSizeGB: 1

net:
  port: 27017
  bindIpAll: true

security:
  authorization: enabled
  keyFile: /run/secrets/replica_keyfile

replication:
  replSetName: rs0

processManagement:
  timeZoneInfo: /usr/share/zoneinfo

setParameter:
  diagnosticDataCollectionEnabled: false
